on: 
  workflow_dispatch:
    inputs:
      testName:
        description: 'test name'     
        required: true
        default: 'demo'
      tags:
        description: 'Test tags'  
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.testName }}"
        echo "Tags: ${{ github.event.inputs.tags }}" 
